### ISSUE TITLE
Problems executing FOC MOTOR CONTROL APP

### ISSUE THREAD

**Issue by aalaba** [Xilinx/foc-motor-ctrl#1]
Hello! I have purchased the Kria KD240 Starter Kit with the Motor Accesory Pack and am trying to have the default application working but am having some problems. 

I am following the steps mentioned in the README.md [here](https://github.com/Xilinx/foc-motor-ctrl) very cautiously but when I get to the last step (executing the app) I get the message _"start_motor_dashboard: command not found"_.

I have attached below the logs I am getting. I have also installed the latest boot firmware following the instructions mentioned [here](https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/1641152513/Kria+SOMs+Starter+Kits#K24-Boot-Firmware-Updates-(Yocto)) and had to install the CXX compiler using the command _sudo apt-get update && sudo apt-get install build-essential_. 

Can someone help me find the problem so that I can get my kit working as soon as possible, please? Thank you!

LOGS: 
[putty_logs.log](https://github.com/user-attachments/files/16850034/putty_logs.log)

**Comment by harshitha-amd** [comment]
Hello!

Thank you for reporting this. The issue is due to a known typo in the README regarding the installation path. Please update the path from `/opt/xilinx/xlnx-app-kd240-foc-motor-ctr/bin` to `/opt/xilinx/xlnx-app-kd240-foc-motor-ctrl/bin` to get the `start_motor_dashboard` command working properly. The README will be updated in the next release. 

You can refer the documentation here for more details - https://xilinx.github.io/kria-apps-docs/kd240/build/html/docs/foc-motor-ctrl/src/app_deployment.html#run-the-motor-control-dashboard-application
